language: node_js
node_js:
  - "6.1"
cache:
  directories:
    - node_modules
addons:
    code_climate:
        repo_token: b46ca6a50a99508e36c35f2eba479d235143169b6905f15098696547dd71d311
after_script:
  - npm run coveralls
  - npm run codeclimate-cover
